---
- hosts: remote 
  become: true
  gather_facts: true
  tasks:
  - name: install httpd
    package: 
      name: httpd
      state: present
    tags: install

  - name: start and enable httpd
    service:
      name: httpd
      state: started
      enabled: true
    tags: enable

  # - name: modify httpd.conf
  #   template:
  #     src: httpd.conf.j2
  #     dest: /etc/httpd/conf/httpd.conf
  #     group: root
  #     owner: root 
  #     mode: 0644
  #   notify: restart_httpd

  - name: enable listen on private ip address
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: '{{ ansible_default_ipv4.address }}:80'
      backrefs: true
    notify: restart_httpd


  - name: restart_httpd
    service:
      name: httpd
      state: restarted
    tags: handlers