---
- hosts: web
  become: true
  gather_facts: true
  tasks:
  - name: install httpd
    package: 
      name: httpd
      state: present
    tags: install

  - name: start and enable httpd
    service:
      name: httpd
      state: started
      enabled: true
    tags: test

  - name: enable listen on private ip address
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: 'Listen {{ ansible_default_ipv4.address }}:80'
      backrefs: true
    notify: restart_httpd
    ignore_errors: true

  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restarted
    tags: handlers
